spring.application.name=events

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/events-db
spring.datasource.username=postgres
spring.datasource.password=postgres

ISSUER=events-api
PRIVATE_KEY=classpath:/private_key.pem
PUBLIC_KEY=classpath:/public_key.pem

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=events.sender.ifce@gmail.com
spring.mail.password=hzndqdffhbkhfcdy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true