CREATE SEQUENCE IF NOT EXISTS classification_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE activities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id    BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    date_time   date,
    duration    INTEGER,
    local       VARCHAR(255),
    CONSTRAINT pk_activities PRIMARY KEY (id)
);

CREATE TABLE certificates
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    enrollment_id   BIGINT                                  NOT NULL,
    validation_code VARCHAR(255),
    emission_date   date,
    CONSTRAINT pk_certificates PRIMARY KEY (id)
);

CREATE TABLE classification
(
    id                     BIGINT       NOT NULL,
    co_classification      VARCHAR(255) NOT NULL,
    co_classification_type VARCHAR(255) NOT NULL,
    CONSTRAINT pk_classification PRIMARY KEY (id)
);

CREATE TABLE enrollments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT,
    numeric_code     VARCHAR(255),
    event_id         BIGINT                                  NOT NULL,
    participant_id   BIGINT                                  NOT NULL,
    enrollment_date  TIMESTAMP WITHOUT TIME ZONE,
    status           VARCHAR(255),
    was_present      VARCHAR(255),
    validation_token VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_enrollments PRIMARY KEY (id)
);

CREATE TABLE events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255),
    initial_date date,
    final_date   date,
    local        VARCHAR(255),
    status       VARCHAR(255),
    is_active    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE person
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    password         VARCHAR(255),
    role             VARCHAR(255),
    participant_type VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

ALTER TABLE enrollments
    ADD CONSTRAINT uc_a5e254aafa9dc0b7d079f4a62 UNIQUE (event_id, participant_id);

ALTER TABLE certificates
    ADD CONSTRAINT uc_certificates_enrollment UNIQUE (enrollment_id);

ALTER TABLE certificates
    ADD CONSTRAINT uc_certificates_validationcode UNIQUE (validation_code);

ALTER TABLE enrollments
    ADD CONSTRAINT uc_enrollments_numericcode UNIQUE (numeric_code);

ALTER TABLE enrollments
    ADD CONSTRAINT uc_enrollments_validationtoken UNIQUE (validation_token);

ALTER TABLE activities
    ADD CONSTRAINT FK_ACTIVITIES_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE certificates
    ADD CONSTRAINT FK_CERTIFICATES_ON_ENROLLMENT FOREIGN KEY (enrollment_id) REFERENCES enrollments (id);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_PARTICIPANT FOREIGN KEY (participant_id) REFERENCES person (id);